name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: make
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: hello-world
          path: hello
